ALTER TABLE TB_EVALU_DESTI_BUSI_INFO ADD BUSI_NOTE VARCHAR2(4000);

CREATE OR REPLACE FUNCTION TESSUSER.FN_FMT_STRTODATE (
    /**
     * =============================================================
     * name   : 날짜 형식 변경
     * author : ntarget
     * date   : 2014.03.31
     * tables : NONE
     * -------------------------------------------------------------
     *
     * @param     vi_strdate        입력값
     * @param     vi_gbn            구분자
     * @return    vo_date           포맷 데이터
     * =============================================================
     */
    vi_strdate              VARCHAR2,
    vi_gbn                  VARCHAR2
)
RETURN VARCHAR2
IS
    vo_date          VARCHAR2(100);
    v_strExpDate     VARCHAR2(100);

BEGIN
    v_strExpDate := REGEXP_REPLACE(vi_strdate, '[^0-9]+', '');

    IF LENGTH(TRIM(v_strExpDate)) = 8 THEN
        vo_date     := REGEXP_REPLACE(v_strExpDate, '(.{4})(.{2})(.{2})', '\1'||vi_gbn||'\2'||vi_gbn||'\3');
    ELSIF LENGTH(TRIM(v_strExpDate)) = 6 THEN
        vo_date     := REGEXP_REPLACE(v_strExpDate, '(.{4})(.{2})', '\1'||vi_gbn||'\2');
    ELSE
        vo_date := v_strExpDate;
    END IF;

    RETURN vo_date;
END FN_FMT_STRTODATE;

CREATE OR REPLACE FUNCTION TESSUSER.FN_GET_CITYAUTH(
    /**
     * =============================================================
     * name   : 주소 코드로 주소명 효출
     * author : LHB
     * date   : 2023.11.03
     * tables : TB_CITYAUTH
     * -------------------------------------------------------------
     *
     * @param     p_code    코드
     * @return    v_codeNm  코드명
     * =============================================================
     */
    p_code    VARCHAR2
)
RETURN VARCHAR2
IS
    v_codeNm VARCHAR2(500);
BEGIN
    v_codeNm := NULL;

    SELECT CITYAUTH_NM INTO v_codeNm
      FROM TB_CITYAUTH
     WHERE CITYAUTH_CD = p_code;

    RETURN v_codeNm;
END;

CREATE OR REPLACE FUNCTION TESSUSER.FN_FMT_DATA (
    /**
     * =============================================================
     * name   : 포맷된 데이터 조회(전화번호, 사업자등록번호).
     * author : ntarget
     * date   : 2014.03.31
     * tables : NONE
     * -------------------------------------------------------------
     *
     * @param     vi_data           입력값
     * @param     vi_type           포맷타입(전화번호 TEL, 사업자등록번호 RNO)
     * @return    vo_fmt_data        포맷 데이터
     * =============================================================
     */
    vi_type              VARCHAR2,
    vi_data              VARCHAR2
)
RETURN VARCHAR2
IS
    vo_fmt_data          VARCHAR2(100);

BEGIN
    vo_fmt_data := null;

    IF TRIM(vi_data) IS NOT NULL THEN
        IF TRIM(vi_type) = 'TEL' THEN
            vo_fmt_data := REGEXP_REPLACE(REGEXP_REPLACE(vi_data,'[^:digit:]]'),'(^02|050[[:digit:]]{1}|[[:digit:]]{3})([[:digit:]]{3,4})([[:digit:]]{4})','\1-\2-\3');
        ELSIF TRIM(vi_type) = 'RNO' THEN
            vo_fmt_data := REGEXP_REPLACE(vi_data, '^([0-9]{3})-?([0-9]{2})-?([0-9]{5})$', '\1-\2-\3');
        ELSIF TRIM(vi_type) = 'NUM' THEN
            vo_fmt_data := REGEXP_REPLACE(vi_data, '[^0-9]+', '');
        ELSIF TRIM(vi_type) = 'NUM2' THEN
            vo_fmt_data := REGEXP_REPLACE(vi_data, '[^.0-9]+', '');
        END IF;
    END IF;

    RETURN vo_fmt_data;
END FN_FMT_DATA;

CREATE SEQUENCE TESSUSER.SEQ_EVALU_BUSI_NO INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999 CYCLE NOCACHE NOORDER;
CREATE SEQUENCE TESSUSER.SEQ_EVALU_DESTI_BUSI_INFO_SN INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NOCYCLE NOCACHE NOORDER;
CREATE TABLE "TESSUSER"."TB_EVALU_DESTI_BUSI_INFO_BACKUP" AS SELECT * FROM "TESSUSER"."TB_EVALU_DESTI_BUSI_INFO";
DROP TABLE "TESSUSER"."TB_EVALU_DESTI_BUSI_INFO";

CREATE TABLE "TESSUSER"."TB_EVALU_DESTI_BUSI_INFO" 
   ("EVALU_BUSI_SN" NUMBER NOT NULL ENABLE, 
    "EVALU_BUSI_NO" VARCHAR2(19), 
    "EVALU_BUSI_NM" VARCHAR2(200) NOT NULL ENABLE,
    "BUSI_MBY_ADDR1" VARCHAR2(50),
    "BUSI_MBY_ADDR2" VARCHAR2(50),
    "BUSI_ADDR1" VARCHAR2(50), 
    "BUSI_ADDR2" VARCHAR2(50), 
    "BUSI_ADDR3" VARCHAR2(100),
    "GPS_X" VARCHAR2(20), 
    "GPS_Y" VARCHAR2(20), 
    "BUSI_TYPE_LEVEL1" VARCHAR2(5), 
    "BUSI_TYPE_LEVEL2" VARCHAR2(5), 
    "BUSI_CATE" VARCHAR2(4), 
    "BUSI_NOTE" VARCHAR2(4000),
    "REGI_ID" VARCHAR2(20), 
    "REGI_DATE" DATE, 
    "UPDT_ID" VARCHAR2(20), 
    "UPDT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE UNIQUE INDEX "TESSUSER"."PK_TB_EVALU_DESTI_BUSI_INFO" ON "TESSUSER"."TB_EVALU_DESTI_BUSI_INFO" ("EVALU_BUSI_SN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
ALTER TABLE "TESSUSER"."TB_EVALU_DESTI_BUSI_INFO" ADD CONSTRAINT "PK_TB_EVALU_DESTI_BUSI_INFO" PRIMARY KEY ("EVALU_BUSI_SN")
  USING INDEX "TESSUSER"."PK_TB_EVALU_DESTI_BUSI_INFO"  ENABLE;

COMMENT ON TABLE TESSUSER.TB_EVALU_DESTI_BUSI_INFO IS '평가대상사업 기본정보';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_INFO.EVALU_BUSI_SN IS '평가대상사업 일련번호';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_INFO.EVALU_BUSI_NO IS '평가대상사업코드';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_INFO.EVALU_BUSI_NM IS '평가대상사업명';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_INFO.BUSI_MBY_ADDR1 IS '시행주체 시도';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_INFO.BUSI_MBY_ADDR2 IS '시행주체 시군구';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_INFO.BUSI_ADDR1 IS '대상지역 시도';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_INFO.BUSI_ADDR2 IS '대상지역 시군구';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_INFO.BUSI_ADDR3 IS '대상지역 상세주소';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_INFO.GPS_X IS 'GPS_X';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_INFO.GPS_Y IS 'GPS_Y';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_INFO.BUSI_TYPE_LEVEL1 IS '사업 구분 1단계';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_INFO.BUSI_TYPE_LEVEL2 IS '사업 구분 2단계';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_INFO.BUSI_CATE IS '사업의유형';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_INFO.BUSI_NOTE IS '사업내용';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_INFO.REGI_ID IS '등록자';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_INFO.REGI_DATE IS '등록일자';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_INFO.UPDT_ID IS '수정자';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_INFO.UPDT_DATE IS '수정일자';

GRANT SELECT ON TREDSUSER.TB_BJD_CODE TO TESSUSER;

CREATE OR REPLACE FUNCTION FN_GET_BJDNM(
    /**
     * =============================================================
     * name   : 법정동 코드로 법정동명 호출
     * author : LHB
     * date   : 2023.11.07
     * tables : TREDSUSER.TB_BJD_CODE
     * -------------------------------------------------------------
     *
     * @param     p_code    코드
     * @return    v_codeNm  코드명
     * =============================================================
     */
    p_code    VARCHAR2
)
RETURN VARCHAR2
IS
    v_codeNm VARCHAR2(500);
    v_str    VARCHAR2(10);
BEGIN
    v_codeNm := NULL;

    SELECT CASE
               WHEN LENGTH(TRIM(p_code)) = 2 THEN SD
               WHEN LENGTH(TRIM(p_code)) = 5 THEN SD||' '||SGG
           END INTO v_codeNm
      FROM "TREDSUSER"."TB_BJD_CODE"
     WHERE BJD_CODE LIKE RPAD(p_code, 10, '0');

    RETURN v_codeNm;
END;

-- TESSUSER.TB_EVALU_DESTI_BUSI_HIST definition
DROP TABLE "TESSUSER"."TB_EVALU_DESTI_BUSI_HIST";
CREATE TABLE "TESSUSER"."TB_EVALU_DESTI_BUSI_HIST" 
   (
    "EVALU_HIST_SN" NUMBER NOT NULL ENABLE,
    "EVALU_HIST_NO" VARCHAR2(19), 
    "EVALU_BUSI_SN" NUMBER NOT NULL ENABLE,
    "EVALU_YEAR" VARCHAR2(4) NOT NULL ENABLE,
    "EVALU_STAGE" VARCHAR2(10) NOT NULL ENABLE, 
    "BUSI_STT_DATE" VARCHAR2(8),
    "BUSI_END_DATE" VARCHAR2(8),
    "BUSI_ADDR1" VARCHAR(50),
    "BUSI_ADDR2" VARCHAR(50),
    "BUSI_ADDR3" VARCHAR(100),
    "MAIN_FCLT" VARCHAR2(1000),
    "BUSI_NOTE" VARCHAR2(4000),
    "TOT_BUSI_EXPS1" NUMBER,
    "TOT_BUSI_EXPS2" NUMBER,
    "TOT_BUSI_EXPS3" NUMBER,
    "PRGR_GUBUN" VARCHAR2(5),
    "REGI_ID" VARCHAR2(20), 
    "REGI_DATE" DATE, 
    "UPDT_ID" VARCHAR2(20), 
    "UPDT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "TESSUSER"."PK_TB_EVALU_DESTI_BUSI_HIST" ON "TESSUSER"."TB_EVALU_DESTI_BUSI_HIST" ("EVALU_HIST_SN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
ALTER TABLE "TESSUSER"."TB_EVALU_DESTI_BUSI_HIST" ADD CONSTRAINT "PK_TB_EVALU_DESTI_BUSI_HIST" PRIMARY KEY ("EVALU_HIST_SN")
  USING INDEX "TESSUSER"."PK_TB_EVALU_DESTI_BUSI_HIST"  ENABLE;

COMMENT ON TABLE TESSUSER.TB_EVALU_DESTI_BUSI_HIST IS '평가대상사업 이력';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST.EVALU_HIST_SN IS '평가대상사업 이력 일련번호';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST.EVALU_HIST_NO IS '평가대상사업 이력 사업코드';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST.EVALU_BUSI_SN IS '평가대상사업 일련번호';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST.EVALU_YEAR IS '평가연도';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST.EVALU_STAGE IS '평가단계';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST.BUSI_STT_DATE IS '사업시작일자';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST.BUSI_END_DATE IS '사업종료일자';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST.BUSI_ADDR1 IS '시도 주소';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST.BUSI_ADDR2 IS '시군구 주소';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST.BUSI_ADDR3 IS '상세 주소';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST.MAIN_FCLT IS '주요시설';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST.BUSI_NOTE IS '사업내용';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST.TOT_BUSI_EXPS1 IS '사업비(국비)';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST.TOT_BUSI_EXPS2 IS '사업비(지방비)';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST.TOT_BUSI_EXPS3 IS '사업비(민자)';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST.PRGR_GUBUN IS '진행구분';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST.REGI_ID IS '등록자';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST.REGI_DATE IS '등록일자';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST.UPDT_ID IS '수정자';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST.UPDT_DATE IS '수정일자';

CREATE SEQUENCE TESSUSER.SEQ_EVALU_DESTI_BUSI_HIST_SN INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NOCYCLE NOCACHE NOORDER;

INSERT INTO SYS_CODE VALUES ('PRGR_GUBUN', 'NONE', '진행구분', NULL, NULL, NULL, NULL, NULL, 0, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('PG10', 'PRGR_GUBUN', '평가의뢰', NULL, NULL, NULL, NULL, NULL, 1, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('PG20', 'PRGR_GUBUN', '의견서 작성', NULL, NULL, NULL, NULL, NULL, 2, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('PG30', 'PRGR_GUBUN', '결과서 작성', NULL, NULL, NULL, NULL, NULL, 3, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('PG40', 'PRGR_GUBUN', '결과통보대기', NULL, NULL, NULL, NULL, NULL, 4, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('PG50', 'PRGR_GUBUN', '결과통보', NULL, NULL, NULL, NULL, NULL, 4, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('PG60', 'PRGR_GUBUN', '이행계획서 작성', NULL, NULL, NULL, NULL, NULL, 5, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('PG90', 'PRGR_GUBUN', '결과승인', NULL, NULL, NULL, NULL, NULL, 6, 'Y', 'hblee', SYSDATE, NULL, NULL);

UPDATE SYS_MENU SET USE_YN = 'N' WHERE MENU_ID = 'MN-MNG0300';


INSERT INTO SYS_CODE VALUES ('BT100', 'BUSI_TYPE_LEVEL', '지역자율계정', 'BUSI_TYPE_LEVEL1', '1', NULL, NULL, NULL, 1, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('BT101', 'BUSI_TYPE_LEVEL', '지역지원계정', 'BUSI_TYPE_LEVEL1', '1', NULL, NULL, NULL, 2, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('BT102', 'BUSI_TYPE_LEVEL', '제주특별자치도계정', 'BUSI_TYPE_LEVEL1', '1', NULL, NULL, NULL, 3, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('BT103', 'BUSI_TYPE_LEVEL', '세종특별자치시계정', 'BUSI_TYPE_LEVEL1', '1', NULL, NULL, NULL, 4, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('BT104', 'BUSI_TYPE_LEVEL', '관광진흥개발기금', 'BUSI_TYPE_LEVEL1', '1', NULL, NULL, NULL, 5, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('BT105', 'BUSI_TYPE_LEVEL', '기타', 'BUSI_TYPE_LEVEL1', '1', NULL, NULL, NULL, 6, 'Y', 'hblee', SYSDATE, NULL, NULL);

INSERT INTO SYS_CODE VALUES ('BT200', 'BT100', '관광자원개발사업', 'BUSI_TYPE_LEVEL2', '2', NULL, NULL, NULL, 1, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('BT210', 'BT101', '광역권관광자원개발', 'BUSI_TYPE_LEVEL2', '2', NULL, NULL, NULL, 1, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('BT211', 'BT101', '관광레저 개발 육성', 'BUSI_TYPE_LEVEL2', '2', NULL, NULL, NULL, 2, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('BT250', 'BT105', '지역발전 투자협약', 'BUSI_TYPE_LEVEL2', '2', NULL, NULL, NULL, 1, 'Y', 'hblee', SYSDATE, NULL, NULL);

INSERT INTO SYS_CODE VALUES ('0110', 'BT200', '관광(단)지 개발', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 1, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0300', 'BT200', '생태녹색관광자원개발', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 2, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0400', 'BT200', '문화관광자원개발', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 3, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0700', 'BT200', '국가여가캠핑장 조성', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 4, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0805', 'BT200', '한옥체험숙박시설 운영지원', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 5, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0810', 'BT200', '관광안내체계 구축', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 6, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0815', 'BT200', '탐방로안내체계 구축', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 7, 'Y', 'hblee', SYSDATE, NULL, NULL);

INSERT INTO SYS_CODE VALUES ('0210', 'BT210', '남해안관광벨트 개발', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 1, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0205', 'BT210', '경북북부 유교문화권 관광개발', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 2, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0230', 'BT210', '지리산권 관광개발', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 3, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0225', 'BT210', '서해안권 광역관광개발', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 4, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0220', 'BT210', '동해안권 광역관광개발', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 5, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0215', 'BT210', '남해안 관광 클러스터', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 6, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0235', 'BT210', '3대 문화권 문화생태 관광기반조성', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 7, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0245', 'BT210', '한반도 생태평화벨트', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 8, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0240', 'BT210', '중부내륙권 광역관광개발', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 9, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0250', 'BT210', '서부내륙권 광역관광개발', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 10, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0255', 'BT210', '충청유교문화권 광역관광개발', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 11, 'Y', 'hblee', SYSDATE, NULL, NULL);

INSERT INTO SYS_CODE VALUES ('0870', 'BT211', '기업도시 진입도로 지원사업', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 1, 'Y', 'hblee', SYSDATE, NULL, NULL);

INSERT INTO SYS_CODE VALUES ('0825', 'BT102', '(시도, 시군구 자율편성사업)', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 1, 'Y', 'hblee', SYSDATE, NULL, NULL);

INSERT INTO SYS_CODE VALUES ('0835', 'BT103', '(시도, 시군구 자율편성사업)', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 1, 'Y', 'hblee', SYSDATE, NULL, NULL);

INSERT INTO SYS_CODE VALUES ('0900', 'BT104', '폐광지역 관광상품개발', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 1, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0905', 'BT104', '지역관광자원개발', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 2, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0910', 'BT104', '계획공모형 지역관광개발', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 3, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0915', 'BT104', '제주관광진흥지원', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 4, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0920', 'BT104', '관광거점도시', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 5, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('0925', 'BT104', '온천지구 관광거점 조성', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 6, 'Y', 'hblee', SYSDATE, NULL, NULL);

INSERT INTO SYS_CODE VALUES ('1000', 'BT250', '국토부 지역발전 투자협약', 'BUSI_TYPE_LEVEL3', '3', NULL, NULL, NULL, 1, 'Y', 'hblee', SYSDATE, NULL, NULL);

INSERT INTO SYS_CODE VALUES ('EVALU_BUDT', 'EVALU_STAGE', '예산요구', NULL, NULL, NULL, NULL, NULL, 1, 'N', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('EVALU_PREV', 'EVALU_STAGE', '사전평가', NULL, NULL, NULL, NULL, NULL, 1, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('EVALU_AFTR', 'EVALU_STAGE', '사후평가', NULL, NULL, NULL, NULL, NULL, 3, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('EVALU_PROG', 'EVALU_STAGE', '집행평가', NULL, NULL, NULL, NULL, NULL, 2, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('EVALU_CENT', 'EVALU_STAGE', '중앙투자심사', NULL, NULL, NULL, NULL, NULL, 5, 'N', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('EVALU_AFMN', 'EVALU_STAGE', '사후모니터링', NULL, NULL, NULL, NULL, NULL, 6, 'N', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('EVALU_COMP', 'EVALU_STAGE', '사전적합성조사', NULL, NULL, NULL, NULL, NULL, 7, 'N', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('EVALU_NBCO', 'EVALU_STAGE', '신규예산편성검토', NULL, NULL, NULL, NULL, NULL, 8, 'N', 'hblee', SYSDATE, NULL, NULL);

UPDATE SYS_MENU SET MENU_NM = '진행중인 평가사업' WHERE MENU_ID = 'MN-BUSI0100';

ALTER TABLE TESSUSER.SYS_CODE MODIFY ADD_COL4 VARCHAR2(200);
ALTER TABLE TESSUSER.SYS_CODE MODIFY ADD_COL5 VARCHAR2(200);

INSERT INTO SYS_CODE VALUES ('FT001', 'FILE_TYPE', '사업설명서 샘플', 'locgov', 'EVALU_PREV', NULL, NULL, 'prev/ft_bizmnl_s.pdf', 1, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT002', 'FILE_TYPE', '사업설명서 양식', 'locgov', 'EVALU_PREV', NULL, NULL, 'prev/ft_bizmnl_f.pdf', 2, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT011', 'FILE_TYPE', '기본계획보고서 샘플', 'locgov', 'EVALU_PREV', NULL, NULL, 'prev/ft_bsc_s.pdf', 3, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT012', 'FILE_TYPE', '기본계획보고서 양식', 'locgov', 'EVALU_PREV', NULL, NULL, 'prev/ft_bsc_f.pdf', 4, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT021', 'FILE_TYPE', '이행계획서 샘플', 'locgov', 'EVALU_PREV', NULL, NULL, 'prev/ft_flfl_s.pdf', 5, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT022', 'FILE_TYPE', '이행계획서 양식', 'locgov', 'EVALU_PREV', NULL, NULL, 'prev/ft_flfl_f.pdf', 6, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT031', 'FILE_TYPE', '서면검토서 샘플', 'evl', 'EVALU_PREV', NULL, NULL, 'prev/ft_evlrvw_s.pdf', 7, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT032', 'FILE_TYPE', '서면검토서 양식', 'evl', 'EVALU_PREV', NULL, NULL, 'prev/ft_evlrvw_f.pdf', 8, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT041', 'FILE_TYPE', '평가지침서 샘플', 'evl', 'EVALU_PREV', NULL, NULL, 'prev/ft_evlmnl_s.pdf', 9, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT042', 'FILE_TYPE', '평가지침서 양식', 'evl', 'EVALU_PREV', NULL, NULL, 'prev/ft_evlmnl_f.pdf', 10, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT051', 'FILE_TYPE', '평가의견서 샘플', 'evl', 'EVALU_PREV', NULL, NULL, 'prev/ft_evlopnn_s.pdf', 11, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT052', 'FILE_TYPE', '평가의견서 양식', 'evl', 'EVALU_PREV', NULL, NULL, 'prev/ft_evlopnn_f.pdf', 12, 'Y', 'hblee', sysdate, NULL, NULL);

INSERT INTO SYS_CODE VALUES ('FT101', 'FILE_TYPE', '사업설명서 샘플', 'locgov', 'EVALU_PROG', NULL, NULL, 'prog/ft_bizmnl_s.pdf', 1, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT102', 'FILE_TYPE', '사업설명서 양식', 'locgov', 'EVALU_PROG', NULL, NULL, 'prog/ft_bizmnl_f.pdf', 2, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT111', 'FILE_TYPE', '기본계획보고서 샘플', 'locgov', 'EVALU_PROG', NULL, NULL, 'prog/ft_bsc_s.pdf', 3, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT112', 'FILE_TYPE', '기본계획보고서 양식', 'locgov', 'EVALU_PROG', NULL, NULL, 'prog/ft_bsc_f.pdf', 4, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT121', 'FILE_TYPE', '이행계획서 샘플', 'locgov', 'EVALU_PROG', NULL, NULL, 'prog/ft_flfl_s.pdf', 5, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT122', 'FILE_TYPE', '이행계획서 양식', 'locgov', 'EVALU_PROG', NULL, NULL, 'prog/ft_flfl_f.pdf', 6, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT131', 'FILE_TYPE', '서면검토서 샘플', 'evl', 'EVALU_PROG', NULL, NULL, 'prog/ft_evlrvw_s.pdf', 7, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT132', 'FILE_TYPE', '서면검토서 양식', 'evl', 'EVALU_PROG', NULL, NULL, 'prog/ft_evlrvw_f.pdf', 8, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT141', 'FILE_TYPE', '평가지침서 샘플', 'evl', 'EVALU_PROG', NULL, NULL, 'prog/ft_evlmnl_s.pdf', 9, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT142', 'FILE_TYPE', '평가지침서 양식', 'evl', 'EVALU_PROG', NULL, NULL, 'prog/ft_evlmnl_f.pdf', 10, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT151', 'FILE_TYPE', '평가의견서 샘플', 'evl', 'EVALU_PROG', NULL, NULL, 'prog/ft_evlopnn_s.pdf', 11, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT152', 'FILE_TYPE', '평가의견서 양식', 'evl', 'EVALU_PROG', NULL, NULL, 'prog/ft_evlopnn_f.pdf', 12, 'Y', 'hblee', sysdate, NULL, NULL);

INSERT INTO SYS_CODE VALUES ('FT201', 'FILE_TYPE', '사업설명서 샘플', 'locgov', 'EVALU_AFTR', NULL, NULL, 'aftr/ft_bizmnl_s.pdf', 1, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT202', 'FILE_TYPE', '사업설명서 양식', 'locgov', 'EVALU_AFTR', NULL, NULL, 'aftr/ft_bizmnl_f.pdf', 2, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT211', 'FILE_TYPE', '기본계획보고서 샘플', 'locgov', 'EVALU_AFTR', NULL, NULL, 'aftr/ft_bsc_s.pdf', 3, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT212', 'FILE_TYPE', '기본계획보고서 양식', 'locgov', 'EVALU_AFTR', NULL, NULL, 'aftr/ft_bsc_f.pdf', 4, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT221', 'FILE_TYPE', '이행계획서 샘플', 'locgov', 'EVALU_AFTR', NULL, NULL, 'aftr/ft_flfl_s.pdf', 5, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT222', 'FILE_TYPE', '이행계획서 양식', 'locgov', 'EVALU_AFTR', NULL, NULL, 'aftr/ft_flfl_f.pdf', 6, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT231', 'FILE_TYPE', '서면검토서 샘플', 'evl', 'EVALU_AFTR', NULL, NULL, 'aftr/ft_evlrvw_s.pdf', 7, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT232', 'FILE_TYPE', '서면검토서 양식', 'evl', 'EVALU_AFTR', NULL, NULL, 'aftr/ft_evlrvw_f.pdf', 8, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT241', 'FILE_TYPE', '평가지침서 샘플', 'evl', 'EVALU_AFTR', NULL, NULL, 'aftr/ft_evlmnl_s.pdf', 9, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT242', 'FILE_TYPE', '평가지침서 양식', 'evl', 'EVALU_AFTR', NULL, NULL, 'aftr/ft_evlmnl_f.pdf', 10, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT251', 'FILE_TYPE', '평가의견서 샘플', 'evl', 'EVALU_AFTR', NULL, NULL, 'aftr/ft_evlopnn_s.pdf', 11, 'Y', 'hblee', sysdate, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('FT252', 'FILE_TYPE', '평가의견서 양식', 'evl', 'EVALU_AFTR', NULL, NULL, 'aftr/ft_evlopnn_f.pdf', 12, 'Y', 'hblee', sysdate, NULL, NULL);

UPDATE SYS_CODE
   SET ADD_COL4 = SUBSTR(ADD_COL5, 6)
 WHERE PARENT_CODE = 'FILE_TYPE';

CREATE SEQUENCE TESSUSER.SEQ_EVALU_DESTI_FILE INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NOCYCLE NOCACHE NOORDER;

INSERT INTO SYS_CODE VALUES ('RFRNC', 'FILE_GUBUN', '참조', '관리자가 업로드한 참조파일', NULL, NULL, NULL, NULL, 1, 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_CODE VALUES ('ULD', 'FILE_GUBUN', '업로드', '사용자가 업로드한 첨부파일', NULL, NULL, NULL, NULL, 2, 'Y', 'hblee', SYSDATE, NULL, NULL);

CREATE TABLE "TESSUSER"."TB_EVALU_DESTI_BUSI_HIST_LOG" 
   (
    "LOG_SN" NUMBER NOT NULL ENABLE,
    "EVALU_HIST_SN" NUMBER NOT NULL ENABLE, 
    "ECT" VARCHAR2(4000),
    "UPDT_ID" VARCHAR2(20), 
    "UPDT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "TESSUSER"."PK_TB_EVALU_DESTI_BUSI_HIST_LOG" ON "TESSUSER"."TB_EVALU_DESTI_BUSI_HIST_LOG" ("LOG_SN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
ALTER TABLE "TESSUSER"."TB_EVALU_DESTI_BUSI_HIST_LOG" ADD CONSTRAINT "PK_TB_EVALU_DESTI_BUSI_HIST_LOG" PRIMARY KEY ("LOG_SN")
  USING INDEX "TESSUSER"."PK_TB_EVALU_DESTI_BUSI_HIST_LOG"  ENABLE;

COMMENT ON TABLE TESSUSER.TB_EVALU_DESTI_BUSI_HIST_LOG IS '평가대상사업 이력 로그';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST_LOG.LOG_SN IS '로그 일련번호';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST_LOG.EVALU_HIST_SN IS '평가대상사업 이력 일련번호';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST_LOG.ECT IS '비고';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST_LOG.UPDT_ID IS '수정자';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_HIST_LOG.UPDT_DATE IS '수정일자';

CREATE SEQUENCE TESSUSER.SEQ_EVALU_DESTI_BUSI_HIST_LOG_SN INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NOCYCLE NOCACHE NOORDER;

INSERT INTO SYS_MENU VALUES ('MN-MNG0230', '참조파일관리', 4, 9, 'MN-MNG0200', NULL, '/mng/listEvaluEnvFile.do', 'N', 'N', 'Y', 'hblee', SYSDATE, NULL, NULL);
INSERT INTO SYS_PROG VALUES ('PG-MNG0203', '참조파일관리 조회', '/mng/listEvaluEnvFile.do', 'url', 'MN-MNG0200', 2, 10, 'hblee', SYSDATE, NULL, NULL);

INSERT INTO SYS_CODE (CODE, PARENT_CODE, CODE_NM, CODE_ODR, USE_YN, REGI_ID, REGI_DATE) VALUES ('ATTH_TYPE', 'NONE', '첨부구분', '0', 'Y', 'jjh', SYSDATE);
INSERT INTO SYS_CODE (CODE, PARENT_CODE, CODE_NM, CODE_ODR, USE_YN, REGI_ID, REGI_DATE) VALUES ('AT01', 'ATTH_TYPE', '사업설명서(한글)', '1', 'Y', 'jjh', SYSDATE);
INSERT INTO SYS_CODE (CODE, PARENT_CODE, CODE_NM, CODE_ODR, USE_YN, REGI_ID, REGI_DATE) VALUES ('AT02', 'ATTH_TYPE', '사업설명서(PDF)', '2', 'Y', 'jjh', SYSDATE);
INSERT INTO SYS_CODE (CODE, PARENT_CODE, CODE_NM, CODE_ODR, USE_YN, REGI_ID, REGI_DATE) VALUES ('AT03', 'ATTH_TYPE', '기본계획', '3', 'Y', 'jjh', SYSDATE);
INSERT INTO SYS_CODE (CODE, PARENT_CODE, CODE_NM, CODE_ODR, USE_YN, REGI_ID, REGI_DATE) VALUES ('AT04', 'ATTH_TYPE', '기타1', '4', 'Y', 'jjh', SYSDATE);
INSERT INTO SYS_CODE (CODE, PARENT_CODE, CODE_NM, CODE_ODR, USE_YN, REGI_ID, REGI_DATE) VALUES ('AT05', 'ATTH_TYPE', '기타2', '5', 'Y', 'jjh', SYSDATE);
INSERT INTO SYS_CODE (CODE, PARENT_CODE, CODE_NM, CODE_ODR, USE_YN, REGI_ID, REGI_DATE) VALUES ('AT06', 'ATTH_TYPE', '서면검토서', '6', 'Y', 'jjh', SYSDATE);
INSERT INTO SYS_CODE (CODE, PARENT_CODE, CODE_NM, CODE_ODR, USE_YN, REGI_ID, REGI_DATE) VALUES ('AT07', 'ATTH_TYPE', '평가의견서', '7', 'Y', 'jjh', SYSDATE);
INSERT INTO SYS_CODE (CODE, PARENT_CODE, CODE_NM, CODE_ODR, USE_YN, REGI_ID, REGI_DATE) VALUES ('AT08', 'ATTH_TYPE', '평가결과서', '8', 'Y', 'jjh', SYSDATE);
INSERT INTO SYS_CODE (CODE, PARENT_CODE, CODE_NM, CODE_ODR, USE_YN, REGI_ID, REGI_DATE) VALUES ('AT09', 'ATTH_TYPE', '이행계획서', '9', 'Y', 'jjh', SYSDATE);