CREATE TABLE "TESSUSER"."TB_EVALU_DESTI_BUSI_MAPPING" 
   ("MAPPING_SN" NUMBER NOT NULL ENABLE, 
	"EVALU_HIST_SN" NUMBER NOT NULL ENABLE, 
	"MFCMM_USER_ID" VARCHAR2(20) NOT NULL ENABLE,
	"OPINION_NOTE"	VARCHAR2(4000),
	"IPM_NOTE" VARCHAR2(4000),
	"REGI_ID" VARCHAR2(20), 
	"REGI_DATE" DATE, 
	"UPDT_ID" VARCHAR2(20),
	"UPDT_DATE" DATE
   );
ALTER TABLE "TESSUSER"."TB_EVALU_DESTI_BUSI_MAPPING" ADD CONSTRAINT "PK_TB_EVALU_DESTI_BUSI_MAPPING" PRIMARY KEY ("MAPPING_SN");

COMMENT ON TABLE TESSUSER.TB_EVALU_DESTI_BUSI_MAPPING IS '평가사업 평가위원 매핑';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_MAPPING.MAPPING_SN IS '매핑 일련번호';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_MAPPING.EVALU_HIST_SN IS '평가사업 일련번호';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_MAPPING.MFCMM_USER_ID IS '평가위원 아이디';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_MAPPING.OPINION_NOTE IS '종합의견';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_MAPPING.IPM_NOTE IS '개선사항';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_MAPPING.REGI_ID IS '등록자';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_MAPPING.REGI_DATE IS '등록일자';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_MAPPING.UPDT_ID IS '수정자';
COMMENT ON COLUMN TESSUSER.TB_EVALU_DESTI_BUSI_MAPPING.UPDT_DATE IS '수정일자';